// Page → module mapping and standard selectors (reference for rbac/pages/*).
(function (global) {
  global.RbacConfig = {
    modules: {
      products: { pageClass: "product-page", tableBodyId: "productTableBody" },
      customer: { pageClass: "customer-page", tableBodyId: "customerTableBody" },
      suppliers: { pageClass: "supplier-page", tableBodyId: "supplierTableBody" },
      quotation: { pageClass: "quotation-page", tableBodyId: "quotationTableBody" },
      new_enquiry: { pageClass: "enquiry-page", tableBodySelector: ".enquiry-table tbody" },
      manage_users: { pageClass: "manage-users-page", tableBodyId: "userTableBody" },
      department_roles: { pageClass: "department-page", tableBodyId: "deptTableBody" },
      company_information: { pageClass: "company-page" },
      sales_order: { pageClass: "sales-order-page" },
      quick_billing: { pageClass: "quick-billing-page" },
      delivery_note: { pageClass: "delivery-note-page" },
      invoice: { pageClass: "invoice-list-page", matcher: () => !!document.getElementById("invoiceTableBody") },
      purchase: { matcher: () => !!document.querySelector(".purchase-wrapper") },
      stock_receipt: { matcher: () => !!document.querySelector(".stock-receipt-container") },
      stock_return: { pageClass: "srn-page" },
      credit_note: { pageClass: "credit-page", formClass: "cn-page", tableBodyId: "creditTbody" },
      debit_note: { pageClass: "debit-page", formClass: "dbn-page", tableBodyId: "debitTbody" },
      payment: { matcher: () => !!document.getElementById("savePaymentBtn") },
      create_role: { matcher: () => !!document.querySelector(".permission-table") },
      create_department: { pageClass: "dept-create-page" },
      product_form: { pageClass: "create-product-page" },
      supplier_form: { matcher: () => !!document.getElementById("supplierForm") },
      customer_form: { matcher: () => /create new customer/i.test((document.querySelector(".customer-page .page-title")?.textContent || "")) },
      import_product: { matcher: () => /import products/i.test((document.querySelector(".import-page .import-title")?.textContent || "")) },
      import_customer: { matcher: () => /import customers/i.test((document.querySelector(".import-page .import-title")?.textContent || "")) },
      enquiry_form: { matcher: () => !!document.getElementById("form-enquiry") },
      quotation_form: { matcher: () => !!document.querySelector(".quotation-full") },
      sales_order_form: { matcher: () => !!document.querySelector(".sales-wrapper") },
      delivery_note_form: { pageClass: "dn2-page" },
      dnr_list: { matcher: () => !!document.getElementById("newDnrBtn") },
      dnr_form: { matcher: () => !!document.querySelector(".dnr-page") && !!document.getElementById("submitBtn") },
      invoice_form: { matcher: () => !!document.getElementById("submitInvoiceBtn") },
      invoice_return_list: { matcher: () => /invoice return list/i.test((document.querySelector(".dn-heading")?.textContent || "")) },
      invoice_return_form: { matcher: () => !!document.getElementById("irSubmitBtn") },
      purchase_form: { matcher: () => !!document.getElementById("poDataContainer") },
      stock_receipt_form: { matcher: () => !!document.querySelector(".stock-container") },
      stock_return_form: { matcher: () => !!document.querySelector(".snr-page") && !!document.getElementById("submitBtn") },
      quick_billing_delete: { pageClass: "qb-del-page" },
    },
    headerCreate: {
      "#addProductBtn": "create",
      "#importBtn": "create",
      "#addCustomerBtn": "create",
      "#importCustomerBtn": "create",
      "#addQuotationBtn": "create",
      "#createUserBtn": "create",
      "#createDeptBtn": "create",
      "#newDeliveryNoteBtn": "create",
      ".manage-header-right .btn-primary": "create",
      ".manage-header-right a.btn-primary": "create",
      ".header .new-btn": "create",
      ".dn-header .dn-btn-primary": "create",
      "#newCreditBtn": "create",
      "#newDebitBtn": "create",
      "#savePaymentBtn": "create",
    },
    submitCreate: {
      ".save-btn": "create",
      "#submitBtn": "create",
      "#submitEnquiryBtn": "create",
      "#submitInvoiceBtn": "create",
      "#submitImport": "create",
      "#confirmOk": "create",
      "button[type='submit']": "create",
    },
    submitEdit: {
      "#saveUserBtn": "edit",
      "#saveProductEditBtn": "edit",
      "#saveEnquiryEditBtn": "edit",
      "#saveDeptEditBtn": "edit",
      "#ackSaveBtn": "edit",
      "#saveCreateGrantBtn": "edit",
      "#grantPermissionBtn": "edit",
    },
  };
})(window);
